# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 800)
        MainWindow.setMinimumSize(QtCore.QSize(480, 800))
        MainWindow.setMaximumSize(QtCore.QSize(480, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/MainForm/icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.MainForm = QtWidgets.QWidget(parent=MainWindow)
        self.MainForm.setMinimumSize(QtCore.QSize(480, 800))
        self.MainForm.setMaximumSize(QtCore.QSize(480, 800))
        self.MainForm.setStyleSheet("background-image: url(:/MainForm/BackGround.png);\n"
"border-image: url(:/MainForm/BackGround.png) stretch stretch;")
        self.MainForm.setObjectName("MainForm")
        self.ExecuteButton = QtWidgets.QPushButton(parent=self.MainForm)
        self.ExecuteButton.setGeometry(QtCore.QRect(80, 380, 331, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.ExecuteButton.setFont(font)
        self.ExecuteButton.setStyleSheet("background-color: rgba(0, 0, 0, 0.5);  /* Чёрный с прозрачностью 50% */\n"
"/* или */\n"
"background-color: #80000000;  /* ARGB: 50% прозрачности */\n"
"color: white;")
        self.ExecuteButton.setObjectName("ExecuteButton")
        self.OutPutLabel = QtWidgets.QLabel(parent=self.MainForm)
        self.OutPutLabel.setGeometry(QtCore.QRect(90, 300, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.OutPutLabel.setFont(font)
        self.OutPutLabel.setStyleSheet("background-color: black;\n"
"justify-content: center;")
        self.OutPutLabel.setText("")
        self.OutPutLabel.setObjectName("OutPutLabel")
        self.InputLine = QtWidgets.QLineEdit(parent=self.MainForm)
        self.InputLine.setGeometry(QtCore.QRect(90, 130, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.InputLine.setFont(font)
        self.InputLine.setStyleSheet("color: white;\n"
"justify-content: center;\n"
"")
        self.InputLine.setText("")
        self.InputLine.setObjectName("InputLine")
        self.label = QtWidgets.QLabel(parent=self.MainForm)
        self.label.setGeometry(QtCore.QRect(90, 40, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white\n"
"")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(parent=self.MainForm)
        self.label_3.setGeometry(QtCore.QRect(110, 500, 271, 151))
        self.label_3.setStyleSheet("image: url(:/MainForm/Github.png);\n"
"")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(parent=self.MainForm)
        self.label_2.setGeometry(QtCore.QRect(180, 670, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.MainForm)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Weather"))
        self.ExecuteButton.setText(_translate("MainWindow", "Узнать температуру"))
        self.label.setText(_translate("MainWindow", "Введите название города"))
        self.label_2.setText(_translate("MainWindow", "whgds1360"))
