# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 640)
        self.MainForm = QtWidgets.QWidget(parent=MainWindow)
        self.MainForm.setStyleSheet("background-color:black")
        self.MainForm.setObjectName("MainForm")
        self.ExecuteButton = QtWidgets.QPushButton(parent=self.MainForm)
        self.ExecuteButton.setGeometry(QtCore.QRect(160, 410, 161, 121))
        self.ExecuteButton.setStyleSheet("background-color: white")
        self.ExecuteButton.setObjectName("ExecuteButton")
        self.OutPutLabel = QtWidgets.QLabel(parent=self.MainForm)
        self.OutPutLabel.setGeometry(QtCore.QRect(50, 70, 381, 61))
        self.OutPutLabel.setStyleSheet("background-color: white")
        self.OutPutLabel.setText("")
        self.OutPutLabel.setObjectName("OutPutLabel")
        self.InputLine = QtWidgets.QLineEdit(parent=self.MainForm)
        self.InputLine.setGeometry(QtCore.QRect(90, 240, 311, 41))
        self.InputLine.setStyleSheet("background-color: white")
        self.InputLine.setObjectName("InputLine")
        MainWindow.setCentralWidget(self.MainForm)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ExecuteButton.setText(_translate("MainWindow", "PushButton"))
