# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 800)
        MainWindow.setMinimumSize(QtCore.QSize(480, 800))
        MainWindow.setMaximumSize(QtCore.QSize(480, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/MainForm/icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.MainForm = QtWidgets.QWidget(parent=MainWindow)
        self.MainForm.setMinimumSize(QtCore.QSize(480, 800))
        self.MainForm.setMaximumSize(QtCore.QSize(480, 800))
        self.MainForm.setStyleSheet("background-image: url(:/MainForm/BackGround.png);\n"
"")
        self.MainForm.setObjectName("MainForm")
        self.ExecuteButton = QtWidgets.QPushButton(parent=self.MainForm)
        self.ExecuteButton.setGeometry(QtCore.QRect(60, 400, 381, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.ExecuteButton.setFont(font)
        self.ExecuteButton.setStyleSheet("background-image: url(:/MainForm/ExecuteButton.png);\n"
"border-radius: 35px;")
        self.ExecuteButton.setText("")
        self.ExecuteButton.setObjectName("ExecuteButton")
        self.OutPutLabel = QtWidgets.QLabel(parent=self.MainForm)
        self.OutPutLabel.setGeometry(QtCore.QRect(40, 90, 421, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.OutPutLabel.setFont(font)
        self.OutPutLabel.setStyleSheet("background-color: white;\n"
"background-image: url(:/MainForm/InputLine.png);\n"
"border-radius: 35px;")
        self.OutPutLabel.setText("")
        self.OutPutLabel.setObjectName("OutPutLabel")
        self.InputLine = QtWidgets.QLineEdit(parent=self.MainForm)
        self.InputLine.setGeometry(QtCore.QRect(40, 300, 421, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.InputLine.setFont(font)
        self.InputLine.setStyleSheet("color: white;\n"
"background-image: url(:/MainForm/InputLine.png);\n"
"border-radius: 35px;\n"
"")
        self.InputLine.setText("")
        self.InputLine.setObjectName("InputLine")
        MainWindow.setCentralWidget(self.MainForm)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Weather"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
